# Single and Multi Dimensional Arrays

In [1]:
import numpy as np

## Single Dimensional Array

In [4]:
print('1. Single dimensional array with all 0s:')
print(np.zeros(5,int))
print('2. Single dimesional array with all 1s:')
print(np.ones(5,int))
print('3. Single dimesional array with random integers:')
print(np.random.randint(1,10,5))
print('4. Single dimesional array with values within a range:')
print(np.arange(1,10))

1. Single dimensional array with all 0s:
[0 0 0 0 0]
2. Single dimesional array with all 1s:
[1 1 1 1 1]
3. Single dimesional array with random integers:
[6 1 7 7 6]
4. Single dimesional array with values within a range:
[1 2 3 4 5 6 7 8 9]


## Multidimensional Array

In [3]:
print('1. Multidimensional array with all 0s:')
print(np.zeros((4,3),int))
print('2. Multidimensional array with all 1s:')
print(np.ones((4,3),int))
print('3. Multidimensional array with random integers:')
print(np.random.randint(1,10,(4,3)))
print('4. Multidimensional array with values within a range:')
print(np.arange(1,10).reshape(3,3))
print('5. Multidimensional array with diagonal elements:')
print(np.eye(4,None,0,int))

1. Multidimensional array with all 0s:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
2. Multidimensional array with all 1s:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
3. Multidimensional array with random integers:
[[4 1 1]
 [2 2 4]
 [2 6 9]
 [5 7 8]]
4. Multidimensional array with values within a range:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
5. Multidimensional array with diagonal elements:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
