# Matrix

In [1]:
import numpy as np

In [3]:
arr = np.random.randn(4,3)
print('Array:')
print(arr)
print('1. Size of the array:')
print(arr.size)
print('2. Size of a particular row of the array (second row)')
print(len(arr[:,2]))
print('3. Size of a particular column of the array (second column)')
print(len(arr[2,:]))
print('4. Taking input from a text file')
with open('Ques5','r') as f:
    l=np.loadtxt(f)
print('Input from the file',l)
print('5. Saving an array to the file')
with open('Ques5','wb') as f:
    np.savetxt(f,arr)

Array:
[[-0.11514466 -0.16820103  1.23030797]
 [ 0.94357603  0.20591613  0.60455225]
 [ 0.18847714 -0.85507326  0.15883477]
 [-0.48859146  1.01562304  2.01548653]]
1. Size of the array:
12
2. Size of a particular row of the array (second row)
4
3. Size of a particular column of the array (second column)
3
4. Taking input from a text file
Input from the file [25.     4.    32.     5.47   2.111 67.   ]
5. Saving an array to the file
