# Operations on Matrices

In [1]:
import numpy as np

In [4]:
matrix1 = np.random.randint(1,10,(3,3))
matrix2 = np.random.randint(1,10,(3,3))
print('Matrix 1:')
print(matrix1)
print('Matrix 2:')
print(matrix2)

Matrix 1:
[[2 9 9]
 [5 3 5]
 [6 5 1]]
Matrix 2:
[[5 3 9]
 [4 1 3]
 [6 8 4]]


## Addition

In [5]:
matrix3=matrix1+matrix2
print('Addition:')
print(matrix3)

Addition:
[[ 7 12 18]
 [ 9  4  8]
 [12 13  5]]


## Subtraction

In [6]:
matrix4=matrix1-matrix2
print('Difference:')
print(matrix4)

Difference:
[[-3  6  0]
 [ 1  2  2]
 [ 0 -3 -3]]


## Multiplication

In [10]:
matrix6=matrix1*matrix2
print('Product:')
print(matrix6)

Product:
[[10 27 81]
 [20  3 15]
 [36 40  4]]


## Display specific rows and columns

In [11]:
print('Specific row and column')
print(matrix1[1:,1:])

Specific row and column
[[3 5]
 [5 1]]
