# Operations on Matrices

In [1]:
import numpy as np

In [5]:
arr=np.random.randn(4,3)
print('Array:')
print(arr)

Array:
[[-0.9936922  -0.96852051  0.44910283]
 [ 0.14579613  0.6747177   0.77601732]
 [ 0.91379979  0.51471121 -1.16813429]
 [-0.62605055 -0.19620029 -1.3037407 ]]


## Absolute Value of the Array

In [10]:
print('1. Absolute Value of the Array')
print(np.absolute(arr))

1. Absolute Value of the Array
[[0.9936922  0.96852051 0.44910283]
 [0.14579613 0.6747177  0.77601732]
 [0.91379979 0.51471121 1.16813429]
 [0.62605055 0.19620029 1.3037407 ]]


## Negative Value of the Array

In [9]:
print('2. Negative Value of the Array')
print(np.negative(arr))

2. Negative Value of the Array
[[ 0.9936922   0.96852051 -0.44910283]
 [-0.14579613 -0.6747177  -0.77601732]
 [-0.91379979 -0.51471121  1.16813429]
 [ 0.62605055  0.19620029  1.3037407 ]]


## Array after deleting a row and a column

In [12]:
print('3. The array after deleting row 2')
print(np.delete(arr,2,0))
print('4. The array after deleting column 2')
print(np.delete(arr,2,1))

3. The array after deleting row 2
[[-0.9936922  -0.96852051  0.44910283]
 [ 0.14579613  0.6747177   0.77601732]
 [-0.62605055 -0.19620029 -1.3037407 ]]
4. The array after deleting column 2
[[-0.9936922  -0.96852051]
 [ 0.14579613  0.6747177 ]
 [ 0.91379979  0.51471121]
 [-0.62605055 -0.19620029]]


## Maximum and Minimum Value of the Array

In [13]:
print('5. Maximum value in the array')
print(np.max(arr))
print('6. Minimum value in the array')
print(np.min(arr))

5. Maximum value in the array
0.9137997924261446
6. Minimum value in the array
-1.3037406969538428


## Sum of elements of the Array

In [14]:
print('7. Sum of all elements')
print(np.sum(arr))
print('8. Sum of all elements (row-wise)')
print(np.sum(arr,0))
print('9. Sum of all elements (column-wise)')
print(np.sum(arr,1))

7. Sum of all elements
-1.7821935475788695
8. Sum of all elements (row-wise)
[-0.56014682  0.02470811 -1.24675483]
9. Sum of all elements (column-wise)
[-1.51310988  1.59653115  0.26037671 -2.12599153]
